[package]
name = "git-fixup"
version = "0.1.6"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
edition = "2018"

[dependencies]
git2 = { version = "0.10.0", default_features = false }
dialoguer = "0.1.0"
structopt = "0.2.8"
console = "0.6.1"
clap = { version = "2.31.2", features = ["wrap_help"] }
