[package]
name = "git-fixup"
version = "0.1.6"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
edition = "2018"

[dependencies]
git2 = { version = "0.13.0", default_features = false }
dialoguer = "0.5.0"
structopt = "0.3"
console = "0.10"
clap = { version = "2.33", features = ["wrap_help"] }
